# This workflow publishes Python package on PyPI when a release is created
# author: Omar.Zapata@cern.ch 2020, etejedor@cern.ch 2022

name: SWAN CI/CD pipeline

on:
  push:
    tags:
       - '*/v*'

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set environnment package name  and version
      run: |
        PACKAGE_TAG=${GITHUB_REF#refs/*/}
        PACKAGE_NAME=$(echo $PACKAGE_TAG | cut -d / -f 1)

        echo "PACKAGE_TAG=$PACKAGE_TAG" >> $GITHUB_ENV
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$(echo $PACKAGE_TAG | cut -d / -f 2)" >> $GITHUB_ENV

        if [ -f 'package.json' ]; then
          echo "PACKAGE_JSON=$(echo 1)" >> $GITHUB_ENV
        fi

        PREV_TAG=$(git describe --tags --match "$PACKAGE_NAME*" --abbrev=0 --exclude "$PACKAGE_TAG" || true)
        [ ! -z "$PREV_TAG" ] && PREV_TAG=$PREV_TAG..
        EXT_LOWERCASE=$(echo $PACKAGE_NAME | tr '[:upper:]' '[:lower:]')
        git --no-pager log $PREV_TAG HEAD --pretty=format:"- %B" -- $PACKAGE_NAME | sed -r "s/($EXT_LOWERCASE|$PACKAGE_NAME): //g" | sed -r "s/\*/  \*/g" > /tmp/release_body.md


    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install build twine

    - name: Build wheel
      run: |
        python -m build

    - name: Publish distribution to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload --repository pypi dist/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: /tmp/release_body.md
        draft: false
        prerelease: false
